# XGBoost BoW Modelling
- Data
    - Domain 1
    - Domain 2
    - Domain 1 & 2

- Data Processing
    - Sequence
    - Bag of Words
        - with n-gram
    - TFIDF
        - with n-gram

- Parameters
    - Tree Depth

- Validation
    - 10-fold cross validation
    
- Visualisation
    - Accuracy Graph
    - Confusion Matrix


In [17]:
# from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.datasets import make_classification
import numpy as np
import json

## 1. Load Data

In [18]:
def load_data(index):
    MACHINE1 = 7
    HUMAN = 8
    text = []
    label = []
    model = []

    if index == 1 or index == 3:
        with open("../../data/domain1_train.json") as f:
            for line in f:
                # read line by line
                data = json.loads(line)

                # add values
                text.append(data["text"])
                label.append(data["label"])
                if data["label"] == 0:
                    model.append(MACHINE1)
                else:
                    model.append(HUMAN)

    if index == 2 or index == 3:
        with open("../../data/domain2_train.json") as f:
            for line in f:
                # read line by line
                data = json.loads(line)

                # add values
                text.append(data["text"])
                label.append(data["label"])
                if data["label"] == 0:
                    model.append(data["model"])
                else:
                    model.append(HUMAN)


    # print(f"Domain{index} length:", len(text))
    
    return text, label, model


In [19]:
print("Domain1 length:", len(load_data(1)[0]))
print("Domain2 length:", len(load_data(2)[0]))
print("Domain1&2 length:", len(load_data(3)[0]))

Domain1 length: 19500
Domain2 length: 14900
Domain1&2 length: 34400


In [20]:
# import pandas as pd

text, label, model = load_data(3)

# df3 = pd.DataFrame({"text":text, "label":label, "model":model})

## 2. Data Preprocessing

#### Create sample data for making vertor space

In [21]:
# def vector_sample(text):
#     # Number of words: 5000
#     sample = [np.arange(5000).tolist()]

#     # For n-gram
#     sample += text

#     return sample

In [22]:
# # Data domain
# d = 1
# print(f"sample size for D{d}:", len(vector_sample(load_data(d)[0])))

#### Vectorize the data

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

def toStr(n):
   return str(n)

def count_vec(text, n_features):
   # Create a Vectorizer Object
   vectorizer = CountVectorizer(preprocessor= toStr, analyzer="word", token_pattern=r"(?u)\b\w+\b", ngram_range=(1, 3), max_features=n_features)

   vectorizer.fit(text)

   # Printing the identified Unique words along with their indices
   # print("Vocabulary: ", vectorizer.vocabulary_)

   # Encode the Document
   vector = vectorizer.transform(text)

   # vector.get_stop_words()

   # Summarizing the Encoded Texts
   # print("Encoded Document is:")
   # print(vector.toarray())

   return vector, vectorizer


In [24]:
# Data domain
d = 1
count_vec(load_data(d)[0], 10000)[0].toarray().shape

(19500, 10000)

## 3. Set Parameters & Train the models

In [25]:
DOMAINS = range(1, 4)
N_FEATURES = range(5000, 20000, 5000)
T_DEPTHS = range(1, 10, 2)


In [28]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from collections import Counter

def BoW_training(domain, features, t_depth):
    # BoW
    d = domain
    f = features
    t = t_depth
    text, label, model = load_data(d)
    text, text_test, model, model_test = train_test_split(text, model, test_size=0.2, random_state=42)

    X, vectorizer = count_vec(text, f)
    X = X.toarray()
    # y = np.array(label).ravel()
    y = np.array(model).ravel()

    # Resampling
    print(f'Original dataset shape {X.shape}')
    print(f'Original dataset samples per class {Counter(y)}')

    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(X, y)
    print(f'Resampled dataset samples per class {Counter(y_res)}')

    clf = XGBClassifier(max_depth=t, random_state=0, objective='multi:softprob')
    clf.fit(X_res, y_res)

    X_test = vectorizer.transform(text_test).toarray()
    y_test = np.array(model_test).ravel()
    return clf, X_test, y_test

## 4. Validation

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd

n = 10
# cv_scores = []
# r2_scores = []
acc_scores = []
c_matrix = []


for d in [3]: #DOMAINS:
    for f in N_FEATURES:
        for t in T_DEPTHS:
            # For BoW
            clf, X, y = BoW_training(d, f, t)

            print(f"For Domain{d} & {f} Features & {t} Depth:")
            print("Shape of X:", X.shape)
            print("Shape of y:", y.shape)
    
            # acc score for categorical ddata
            y_pred = clf.predict(X)
            acc_scores.append(accuracy_score(y, y_pred))
            print("Accuracy Score\n", acc_scores[-1])

            # Confusion matrix
            c_matrix.append(confusion_matrix(y, y_pred))
            print("Confusion Matirx\n", c_matrix[-1])

            # Cross-validation score
            # cv_scores.append(cross_val_score(clf, X, y, cv=n))
            # print("CV Score\n", cv_scores[-1], "\n")

            # To csv
            cv_result = pd.DataFrame([acc_scores[-1]], index=["acc"], columns=["scores"])
            cv_result.to_csv(f"../../data/results/XGB_mc/XGB-CV-D{d}_F{f}T{t}.csv")
            cm_result = pd.DataFrame(c_matrix[-1])
            cm_result.to_csv(f"../../data/results/XGB_mc/XGB-CM-D{d}_F{f}T{t}.csv")


Original dataset shape (27520, 5000)
Original dataset samples per class Counter({8: 9509, 7: 7754, 0: 1917, 1: 1894, 3: 1885, 2: 1864, 6: 1437, 4: 634, 5: 626})
Resampled dataset samples per class Counter({2: 9509, 7: 9509, 6: 9509, 8: 9509, 1: 9509, 3: 9509, 0: 9509, 4: 9509, 5: 9509})
For Domain3 & 5000 Features & 1 Depth:
Shape of X: (6880, 5000)
Shape of y: (6880,)
Accuracy Score
 0.6406976744186047
Confusion Matirx
 [[  66   40  120   71   57   39   36    8   10]
 [  19  299   31   28   21    4   27   22   12]
 [  59   57  111   87   78   36   34    4    9]
 [  71   61  104   85   72   36   30    5    9]
 [   2    7    0    0   83   30   33    0    0]
 [   3    8    0    0   64   58   21    0    0]
 [   4    5    6    4   38   21  247    0    1]
 [   6  134   10    4    1    3    1 1504  333]
 [  54   35  122   63   68   39   22   33 1955]]
Original dataset shape (27520, 5000)
Original dataset samples per class Counter({8: 9509, 7: 7754, 0: 1917, 1: 1894, 3: 1885, 2: 1864, 6: 1437

## 5. Visualisation

In [ ]:
y_pred
y
# 0 vs 1 
# tfidf


array([1, 1, 1, ..., 0, 0, 0])